# Site
name: 'Barts Review Website'
description: 'BRW is my personal review/recommendation site for all kinds of cool stuff.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/opensource_review'
disqus: 'demowebsite'
email: 'brwillems@gmail.com'
mailchimp-list: ''

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    bart:
      name:           Bart
      site:           https://github.com/bart-r-willems
      avatar:         /assets/images/headshot_small.jpg
      bio:            "Hi, I am Bart. I hope you like my reviews!"
      email:          brwillems@gmail.com
      twitter:        https://twitter.com/bart_r_willems

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: bart
      avatar: /assets/images/headshot_small.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]